### ISSUE TITLE
Backport of Helm modification to add support of custom path for kubelet.

### ISSUE THREAD

**Issue by laghoule** [christian-schlichtherle/synology-csi-chart#11]
Can you backport this MR from the SynologyOpenSource repo?
https://github.com/SynologyOpenSource/synology-csi/pull/57

Thanks

**Comment by chris-sanders** [comment]
I've just run across this as well. I saw the config in the upstream and didn't even notice that this isn't in the hosted chart. This impacts k3s, k0s, and microk8s can we get a release with the config included or is it available somewhere else?

**Comment by chris-sanders** [comment]
I was going to see if there was anything to do but the PR already exists, so I've just thrown it into a helm repo so I can use it until it's released.

- name: synology-csi
  version: '0.9.8-SNAPSHOT'
  repository: https://chris-sanders.github.io/helm-charts

**Comment by christian-schlichtherle** [comment]
This change was merged and will be released soon.
