### ISSUE TITLE
alpine linux not supported

### ISSUE THREAD

**Issue by aSauerwein** [christian-schlichtherle/synology-csi-chart#12]
Hi, 

i tried this provider and could it be that alpine linux is not supported ? 
the LUNs are created and mounted via iSCSI. So that's fine. 
But when I try to use this pvc in a pod it is stuck in pending
reason
```
  Warning  FailedMount             6m10s (x20 over 37m)  kubelet                  MountVolume.MountDevice failed for volume "pvc-0b37a8dc-16fb-4b92-a8a6-4c45d66e3363" : rpc error: code = Internal desc = rpc error: code = Internal desc = Can't find device path [/dev/disk/by-path/ip-192.168.10.200:3260-iscsi-iqn.2000-01.com.synology:media1.pvc-0b37a8dc-16fb-4b92-a8a6-4c45d66e3363-lun-1]: file does not exist
  ```
  
  from what I see is that the csi plugin tries to access the disk by `/dev/disk/by-path` which is created by udev and there is no systemd/udev in alpine linux. 
  
  is that true ? could we update the docs somewhere that systemd/udev is mandatory ?

**Comment by aSauerwein** [comment]
sorry, wanted to open this issue on SynologyOpenSource/synology-csi and not here.

**Comment by christian-schlichtherle** [comment]
No problem. On the subject matter, I believe that Alpine Linux in the container should not be a problem. However, on the host that's a different story.
