### ISSUE TITLE
How to allow volumeMounts to allow non-root containers to write to them?

### ISSUE THREAD

**Issue by chrisbsmith** [christian-schlichtherle/synology-csi-chart#14]
This is just a question, and probably better for a discussion; but how have you gotten the CSI driver to allow non-root containers to write to the mount point? I have tried setting the `securityContext` but without any luck.

**Comment by chrisbsmith** [comment]
Well, I found this on the next google after I opened this issue and it appears to be working.

https://github.com/kubernetes/examples/issues/260#issuecomment-534160265

**Comment by ericchu94** [comment]
fyi I was able to get fsGroup working by specifying fsType in my StorageClass

**Comment by christian-schlichtherle** [comment]
For SMB you can add the mount option `noperm` to the storage class.
