### ISSUE TITLE
node kubeletpath not available in last chart

### ISSUE THREAD

**Issue by zoc** [christian-schlichtherle/synology-csi-chart#15]
Hi @christian-schlichtherle,

I'm currently trying to install the chart v0.9.7. As this is on a microk8s install, I need to change the kubelet path. I've seen that you added the node/kubeletpath parameter in one of your last commits in the repo, but it does not seem to be present in the v0.9.7 (latest available) of the chart.

Do you have any plan to release an updated version of the chart soon ?

Thanks.

**Comment by christian-schlichtherle** [comment]
I'm sorry for the long delay. Version 0.9.8 has been released just now.
