### ISSUE TITLE
Couldn't find any host available to create volume

### ISSUE THREAD

**Issue by jrowinski3d** [christian-schlichtherle/synology-csi-chart#4]
Using general defaults for the values and updating my connection strings in the values.yml I am receiving this error:

```bash
Failed to create Volume: rpc error: code = Internal desc = Failed to get available location, err: DSM Api error. Error code:105
GRPC error: rpc error: code = Internal desc = Couldn't find any host available to create Volume
```

Any idea whats happening here? I saw a previous issue where updating the parameters to the StorageClass was the solution but it doesn't seem to have the same resolution for me.

https://github.com/christian-schlichtherle/synology-csi-chart/issues/1

Thanks for any help!

**Comment by christian-schlichtherle** [comment]
This error message usually means that your connection parameters are wrong. Please check your network, host name, username, PPW and so on.

**Comment by jrowinski3d** [comment]
@christian-schlichtherle ty for your prompt reply.

Problem was with the `path` I had defined in the StorageClass, as well as the user didn't have the appropriate rights for the connection. My **admin** can connect but my other user cannot. Still looking into which permission determines that
