### ISSUE TITLE
Semantic versioning issues with k3s

### ISSUE THREAD

**Issue by cjbottaro** [christian-schlichtherle/synology-csi-chart#8]
I'm giving k3s a shot and am having problems installing the chart.

> Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.20.0, >= 1.20.0-0 which is incompatible with Kubernetes v1.27.3-k3s1

Changing `Chart.yaml` to:
```yaml
kubeVersion: '>= 1.20.0-0'
```

Fixes the issue.

I _think_ that`kubeVersion` will also work with normal Koob versions, such as `1.27.3`.

**Comment by christian-schlichtherle** [comment]
I’m using K3s all the time, although we’re still at v1.26.7+k3s1. Looking closer at your version information, it doesn’t look correct: It should be `v1.27.3+k3s1`, not `1.27.3-k3s1` - mind the difference of `+` versus `-`. Indeed, using `-` would indicate a pre-release, which changes the semantics (pun intended).

**Comment by cjbottaro** [comment]
So is this like a packaging issue? I'm using k3s on Alpine via their package manager:
https://pkgs.alpinelinux.org/package/v3.18/community/x86_64/k3s

```
$ kubectl get nodes
NAME        STATUS   ROLES                  AGE   VERSION
firebrand   Ready    control-plane,master   76d   v1.27.3-k3s1
```

I'm not sure I can change the reported version to `v1.27.3+k3s1`.

Thanks for the help.

**Comment by christian-schlichtherle** [comment]
This is how it looks for me:

```
$ kubectl get nodes
NAME          STATUS   ROLES                  AGE    VERSION
beta-da0      Ready    control-plane,master   151d   v1.26.9+k3s1
```

Mind the `+` character in `v1.26.9+k3s1`. This is correct semantic versioning where `+k3s1` indicates build metadata, whereas `-k3s1` would indicate a pre-release. See point 10 of the [semver spec](https://semver.org).

I recommend to report this issue upstream to the package maintainers of Alpine.
